import type { Metadata } from "next";
import "./globals.css";
import { StepProvider } from '@/app/context/StepContext';
import { CanvasProvider } from "./context/CanvasContext";
import Header from "@/components/Header";
import { Instrument_Sans } from 'next/font/google';
import { Inter } from 'next/font/google';
import { Figtree } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-figtree',
});

const instrument = Instrument_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // include the weights you use
  display: 'swap',
  variable: '--font-instrument', // optional: for Tailwind config
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${instrument.variable} ${inter.variable} ${figtree.variable}`}>
      <body
        className={`antialiased bg-[#121212]`}
      >
        <StepProvider>
          <CanvasProvider>
            <div className="font-sans min-h-screen text-white flex flex-col bg-[#121212]">
              <Header />
              {children}
            </div>
          </CanvasProvider>
        </StepProvider>
      </body>
    </html>
  );
}
